const Elevator = require('./elevator.js');
const Person = require('./person.js');
let elevator = new Elevator();
// elevator.log();
elevator.update();
elevator.start();
// elevator.stop();
elevator.call(new Person('Diana',0,2));
elevator.call(new Person('Gema',1,6));
elevator.floorUp();
elevator.floorUp();
elevator.floorUp();
elevator.call(new Person('Pepito',5,0));
elevator.floorUp();
elevator.floorUp();
elevator.floorUp();
elevator.floorDown();
elevator.floorDown();
elevator.floorDown();
elevator.floorDown();
elevator.floorDown();
elevator.floorDown();
elevator.stop();
// elevator.log();
// elevator.floorDown();
// elevator.log();
